#source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'NetworkManager_Example' do
  inhibit_all_warnings!
  
  pod 'NetworkManager/Cache', :path => '../'
  
  
  pod 'SwiftyBeaver',:configurations => ['Debug']

  target 'NetworkManager_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
